metric_collector:
  enable: true
  http_client:
    url: "https://prometheus.demo.do.prometheus.io"

rules_collectors:
  - enable: true
    prometheus_client:
      url: "https://prometheus.demo.do.prometheus.io"

perses_collector:
  enable: true
  perses_client:
    url: "https://demo.perses.dev"
